const data = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg/400px-2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg",
    title: "Mazda MX-5",
    start_production: 1989,
    class: "Sports car Roadster",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 2,
    mileage: "25 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg/400px-2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg",
    title: "Porsche Cayenne",
    start_production: 2002,
    class: "Mid-size luxury crossover SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "22 mpg",
    rent: 450,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG/400px-Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG",
    title: "Vauxhall Chevette",
    start_production: 1975,
    class: "Supermini",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "20 mpg",
    rent: 150,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ford_Crown_Victoria_LX.jpg/400px-Ford_Crown_Victoria_LX.jpg",
    title: "Ford Crown Victoria",
    start_production: 1955,
    class: "Full-size Ford",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 6,
    mileage: "18 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Plymouth_Superbird.jpg/400px-Plymouth_Superbird.jpg",
    title: "Plymouth Superbird",
    start_production: 1970,
    class: "Muscle car(today) and Race car(Past)",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 2,
    mileage: "12 mpg",
    rent: 500,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/2nd-Saab-9000-hatch.jpg/400px-2nd-Saab-9000-hatch.jpg",
    title: "Saab 9000",
    start_production: 1984,
    class: "Executive car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/2003-2005_Pontiac_Sunfire.jpg/400px-2003-2005_Pontiac_Sunfire.jpg",
    title: "Pontiac Sunfire",
    start_production: 1994,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "28 mpg",
    rent: 250,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/1971_AMC_Javelin_SST_red_Kenosha_street.JPG/400px-1971_AMC_Javelin_SST_red_Kenosha_street.JPG",
    title: "AMC Javelin",
    start_production: 1967,
    class: "Pony car, Muscle car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 4,
    mileage: "15 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jaguar_X-Type_Estate_front_20080731.jpg/400px-Jaguar_X-Type_Estate_front_20080731.jpg",
    title: "Jaguar X-Type",
    start_production: 2001,
    class: "Compact executive car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "22 mpg",
    rent: 380,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VW_Phaton_%282._Facelift%29_%E2%80%93_Frontansicht%2C_7._Mai_2011%2C_D%C3%BCsseldorf.jpg/400px-VW_Phaton_%282._Facelift%29_%E2%80%93_Frontansicht%2C_7._Mai_2011%2C_D%C3%BCsseldorf.jpg",
    title: "Volkswagen Phaeton",
    start_production: 2002,
    class: "Full-size luxury car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "20 mpg",
    rent: 550,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Pontiac_G6.jpg/400px-Pontiac_G6.jpg",
    title: "Pontiac G6",
    start_production: 2004,
    class: "Midsize",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "26 mpg",
    rent: 320,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Ford500a.JPG/400px-Ford500a.JPG",
    title: "Ford Five Hundred",
    start_production: 2004,
    class: "Full-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "21 mpg",
    rent: 290,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/PontiacSolstice.jpg/400px-PontiacSolstice.jpg",
    title: "Pontiac Solstice",
    start_production: 2005,
    class: "Roadster, coupe",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 2,
    mileage: "29 mpg",
    rent: 380,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Fiat_tipo_f.jpg/400px-Fiat_tipo_f.jpg",
    title: "Fiat Tipo",
    start_production: 1988,
    class: "Small family car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "23 mpg",
    rent: 270,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/1985-89_Plymouth_Reliant_K_LE.png/400px-1985-89_Plymouth_Reliant_K_LE.png",
    title: "Plymouth Reliant",
    start_production: 1981,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "20 mpg",
    rent: 250,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/1978_chevette.JPG/400px-1978_chevette.JPG",
    title: "Chevrolet Chevette",
    start_production: 1975,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "18 mpg",
    rent: 200,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Seat_Leon_1.4_TSI_Start%26Stop_Style_%28III%29_%E2%80%93_Frontansicht%2C_10._August_2013%2C_Ratingen.jpg/400px-Seat_Leon_1.4_TSI_Start%26Stop_Style_%28III%29_%E2%80%93_Frontansicht%2C_10._August_2013%2C_Ratingen.jpg",
    title: "SEAT León",
    class: "Small family car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "24 mpg",
    rent: 280,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Chevrolet_Corsica_1994.jpg/400px-Chevrolet_Corsica_1994.jpg",
    title: "Chevrolet Corsica",
    start_production: 1987,
    class: "Compact car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "22 mpg",
    rent: 260,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/1992_MX3_V6_24V.jpg/400px-1992_MX3_V6_24V.jpg",
    title: "Mazda MX-3",
    start_production: 1991,
    class: "Sport compact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "25 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/2000_TVR_Tuscan_4.0_Speed_Six_by_The_Car_Spy.jpg/400px-2000_TVR_Tuscan_4.0_Speed_Six_by_The_Car_Spy.jpg",
    title: "TVR Tuscan Speed Six",
    start_production: 1999,
    class: "Sports car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 2,
    mileage: "20 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Aston_Martin_DB9_coupe_02.jpg/400px-Aston_Martin_DB9_coupe_02.jpg",
    title: "Aston Martin DB9",
    start_production: 2004,
    class: "Grand tourer",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 2,
    mileage: "18 mpg",
    rent: 600,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Pontiac_Catalina_front.jpg/400px-Pontiac_Catalina_front.jpg",
    title: "Pontiac Catalina",
    start_production: 1950,
    class: "Full-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 6,
    mileage: "15 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Oldsmobile_Toronado_0003.jpg/400px-Oldsmobile_Toronado_0003.jpg",
    title: "Oldsmobile Toronado",
    start_production: 1965,
    class: "Full-size personal luxury car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 6,
    mileage: "13 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Chrysler_Cirrus_--_01-27-2012.jpg/400px-Chrysler_Cirrus_--_01-27-2012.jpg",
    title: "Chrysler Cirrus",
    start_production: 1994,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "23 mpg",
    rent: 280,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/VW_Corrado_-_standard.jpg/400px-VW_Corrado_-_standard.jpg",
    title: "Volkswagen Corrado",
    start_production: 1988,
    class: "Sport compact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "20 mpg",
    rent: 320,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Mercedes_R_350_CDI_4MATIC_Lang_%28V251%29_Facelift_front_20101017.jpg/400px-Mercedes_R_350_CDI_4MATIC_Lang_%28V251%29_Facelift_front_20101017.jpg",
    title: "Mercedes-Benz R-Class",
    class: "Full-size CUV / Large MPV",
    fuel: "Diesel",
    transmission: "Automatic",
    capacity: 7,
    mileage: "26 mpg",
    rent: 650,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Volvo_V50_1.6_D.jpg/400px-Volvo_V50_1.6_D.jpg",
    title: "Volvo V50",
    start_production: 2004,
    class: "Compact / Small family car",
    fuel: "Diesel",
    transmission: "Automatic",
    capacity: 5,
    mileage: "30 mpg",
    rent: 380,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg/400px-Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg",
    title: "Audi TT",
    class: "Sport compact Sports car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 4,
    mileage: "27 mpg",
    rent: 420,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/VW_Touareg_Exclusive_V6_TDI_BlueMotion_Technology_%28II%29_%E2%80%93_Frontansicht%2C_3._Juli_2013%2C_M%C3%BCnster.jpg/400px-VW_Touareg_Exclusive_V6_TDI_BlueMotion_Technology_%28II%29_%E2%80%93_Frontansicht%2C_3._Juli_2013%2C_M%C3%BCnster.jpg",
    title: "Volkswagen Touareg",
    start_production: 2002,
    class: "Mid-size luxury crossover SUV",
    fuel: "Diesel",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 500,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Red92VR4rear.jpg/400px-Red92VR4rear.jpg",
    title: "Mitsubishi GTO",
    start_production: 1990,
    class: "Sports car, grand tourer",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "19 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Cadillac_Cimarron_2_--_07-01-2009.jpg/400px-Cadillac_Cimarron_2_--_07-01-2009.jpg",
    title: "Cadillac Cimarron",
    start_production: 1981,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "16 mpg",
    rent: 280,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/1991_Daytona_CS.JPG/400px-1991_Daytona_CS.JPG",
    title: "Dodge Daytona",
    start_production: 1984,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 4,
    mileage: "20 mpg",
    rent: 250,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Cadillac_Allante.jpg/400px-Cadillac_Allante.jpg",
    title: "Cadillac Allanté",
    start_production: 1986,
    class: "Luxury roadster",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 2,
    mileage: "18 mpg",
    rent: 450,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Audi_S8_%28D4%2C_Facelift%29_%E2%80%93_Frontansicht%2C_9._M%C3%A4rz_2013%2C_W%C3%BClfrath.jpg/400px-Audi_S8_%28D4%2C_Facelift%29_%E2%80%93_Frontansicht%2C_9._M%C3%A4rz_2013%2C_W%C3%BClfrath.jpg",
    title: "Audi S8",
    start_production: 1996,
    class: "Full-size luxury sedan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "19 mpg",
    rent: 600,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/1998FordWindstar.jpg/400px-1998FordWindstar.jpg",
    title: "Ford Windstar",
    start_production: 1994,
    class: "Minivan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 7,
    mileage: "20 mpg",
    rent: 320,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/1993-1997_Dodge_Intrepid_%28first_generation%29.jpg/400px-1993-1997_Dodge_Intrepid_%28first_generation%29.jpg",
    title: "Dodge Intrepid",
    start_production: 1992,
    class: "Full-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 6,
    mileage: "21 mpg",
    rent: 280,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Daewoo_Lanos_1.6_SX_hatch_rear.jpg/400px-Daewoo_Lanos_1.6_SX_hatch_rear.jpg",
    title: "Daewoo Lanos",
    start_production: 1996,
    class: "Subcompact car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "27 mpg",
    rent: 200,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Alfa_Romeo_166_V6.jpg/400px-Alfa_Romeo_166_V6.jpg",
    title: "Alfa Romeo 166",
    start_production: 1998,
    class: "Executive car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "20 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/2005_Peugeot_407_ST_HDi_Executive_sedan_%282015-07-09%29_01.jpg/400px-2005_Peugeot_407_ST_HDi_Executive_sedan_%282015-07-09%29_01.jpg",
    title: "Peugeot 407",
    start_production: 2004,
    class: "Large family car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "28 mpg",
    rent: 250,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Simca_Chrysler_Horizon_GLS_1979.jpg/400px-Simca_Chrysler_Horizon_GLS_1979.jpg",
    title: "Simca-Talbot Horizon",
    start_production: 1978,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "30 mpg",
    rent: 150,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/OPEL-VAUX-SINTRA-A.jpg/400px-OPEL-VAUX-SINTRA-A.jpg",
    title: "Opel Sintra",
    start_production: 1996,
    class: "Large MPV",
    fuel: "Diesel",
    transmission: "Automatic",
    capacity: 7,
    mileage: "25 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Fiat_Stilo_front_20080711.jpg/400px-Fiat_Stilo_front_20080711.jpg",
    title: "Fiat Stilo",
    start_production: 2001,
    class: "Small family car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "26 mpg",
    rent: 220,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Ford_Fairmont_sedan_2.jpg/400px-Ford_Fairmont_sedan_2.jpg",
    title: "Ford Fairmont",
    start_production: 1978,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 200,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/1990_Dodge_Omni.JPG/400px-1990_Dodge_Omni.JPG",
    title: "Dodge Omni",
    start_production: 1977,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "29 mpg",
    rent: 180,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/00-02_Saturn_L-Series_sedan.jpg/400px-00-02_Saturn_L-Series_sedan.jpg",
    title: "Saturn L-Series",
    start_production: 1999,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "27 mpg",
    rent: 270,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Saturn_Ion_--_07-09-2009.jpg/400px-Saturn_Ion_--_07-09-2009.jpg",
    title: "Saturn Ion",
    start_production: 2002,
    class: "Compact car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "31 mpg",
    rent: 240,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/1996-1999_Saturn_SL2_--_03-16-2012.JPG/400px-1996-1999_Saturn_SL2_--_03-16-2012.JPG",
    title: "Saturn S-Series",
    start_production: 1991,
    class: "Compact car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "29 mpg",
    rent: 220,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Chrysler_E_Class%2C_1984.png/400px-Chrysler_E_Class%2C_1984.png",
    title: "Chrysler E-Class",
    start_production: 1982,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "26 mpg",
    rent: 260,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Plymouth_Caravelle%2C_83-85.png/400px-Plymouth_Caravelle%2C_83-85.png",
    title: "Plymouth Caravelle",
    start_production: 1985,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "25 mpg",
    rent: 240,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/1984_Dodge_600_ES_Turbo.jpg/400px-1984_Dodge_600_ES_Turbo.jpg",
    title: "Dodge 600",
    start_production: 1983,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 220,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/%2782_Dodge_400_Coupe_%28Orange_Julep%29.JPG/400px-%2782_Dodge_400_Coupe_%28Orange_Julep%29.JPG",
    title: "Dodge 400",
    start_production: 1981,
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "23 mpg",
    rent: 210,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/1990_Plymouth_Laser_RS_Turbo_red.jpg/400px-1990_Plymouth_Laser_RS_Turbo_red.jpg",
    title: "Plymouth Laser",
    start_production: 1989,
    class: "Sport compact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "27 mpg",
    rent: 180,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/2002-2004_Chrysler_300M_--_05-23-2012.JPG/400px-2002-2004_Chrysler_300M_--_05-23-2012.JPG",
    title: "Chrysler 300M",
    start_production: 1998,
    class: "Full-size luxury sports sedan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "20 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/1995_Vision_TSi_sedan.jpg/400px-1995_Vision_TSi_sedan.jpg",
    title: "Eagle Vision",
    start_production: 1993,
    class: "Full-size luxury sports sedan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "22 mpg",
    rent: 330,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Chrysler-Concorde-Limited.jpg/400px-Chrysler-Concorde-Limited.jpg",
    title: "Chrysler Concorde",
    start_production: 1993,
    class: "Full-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 6,
    mileage: "23 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/1992_Eagle_Premier_ES_Limited.jpg/400px-1992_Eagle_Premier_ES_Limited.jpg",
    title: "Eagle Premier",
    start_production: 1987,
    class: "Full-size luxury car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 320,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Lancia_Thema_8.32_Ferrari.jpg/400px-Lancia_Thema_8.32_Ferrari.jpg",
    title: "Lancia Thema",
    start_production: 1984,
    class: "Executive car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "25 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/en/7/7e/76_Pontiac_Astre.jpg",
    title: "Pontiac Astre",
    start_production: 1972,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "31 mpg",
    rent: 160,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Vega_clay_model.jpg/400px-Vega_clay_model.jpg",
    title: "Chevrolet Vega",
    start_production: 1970,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "28 mpg",
    rent: 150,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Oldsmobile_Firenza_coupe_2.jpg/400px-Oldsmobile_Firenza_coupe_2.jpg",
    title: "Oldsmobile Firenza",
    start_production: 1982,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "26 mpg",
    rent: 200,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/18/75_Chevy_Monza_2%2B2.jpg",
    title: "Chevrolet Monza",
    start_production: 1974,
    class: "Subcompact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "29 mpg",
    rent: 170,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW_6er_Coup%C3%A9_Facelift_20090808_front.JPG/400px-BMW_6er_Coup%C3%A9_Facelift_20090808_front.JPG",
    title: "BMW 6 Series (E63)",
    start_production: 2003,
    class: "Grand tourer",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 4,
    mileage: "23 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Chevrolet_Citation_II_front.jpg/400px-Chevrolet_Citation_II_front.jpg",
    title: "Chevrolet Citation",
    start_production: 1980,
    class: "Compact",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "25 mpg",
    rent: 220,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/96-98_Mercury_Villager_--_12-26-2009.jpg/400px-96-98_Mercury_Villager_--_12-26-2009.jpg",
    title: "Mercury Villager",
    start_production: 1992,
    class: "Minivan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 7,
    mileage: "22 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Nissan350Z-01.jpg/400px-Nissan350Z-01.jpg",
    title: "Nissan 350Z",
    start_production: 2002,
    class: "Sports car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 2,
    mileage: "23 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Hummer_H2_black.JPG/400px-Hummer_H2_black.JPG",
    title: "Hummer H2",
    start_production: 2002,
    class: "Full-size SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 7,
    mileage: "12 mpg",
    rent: 500,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Cadillac_XLR_2006.jpg/400px-Cadillac_XLR_2006.jpg",
    title: "Cadillac XLR",
    start_production: 2003,
    class: "Luxury roadster",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 2,
    mileage: "19 mpg",
    rent: 450,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cadillac--STS.jpg/400px-Cadillac--STS.jpg",
    title: "Cadillac STS",
    start_production: 2005,
    class: "Mid-size luxury sedan",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "21 mpg",
    rent: 400,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/04-07_Buick_Rendezvous_.jpg/400px-04-07_Buick_Rendezvous_.jpg",
    title: "Buick Rendezvous",
    start_production: 2001,
    class: "Mid-size crossover SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "22 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/CT2007SciontC.jpg/400px-CT2007SciontC.jpg",
    title: "Scion tC",
    start_production: 2004,
    class: "Sport compact",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "29 mpg",
    rent: 250,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/97-99_Cadillac_Catera_.jpg/400px-97-99_Cadillac_Catera_.jpg",
    title: "Cadillac Catera",
    start_production: 1997,
    class: "Full-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "24 mpg",
    rent: 300,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Fiat_Coup%C3%A9_front_20090604.jpg/400px-Fiat_Coup%C3%A9_front_20090604.jpg",
    title: "Fiat Coupé",
    start_production: 1993,
    class: "Sports car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "27 mpg",
    rent: 220,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/2002-05_Pontiac_Aztek.jpg/400px-2002-05_Pontiac_Aztek.jpg",
    title: "Pontiac Aztek",
    start_production: 2000,
    class: "Mid-size crossover SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "20 mpg",
    rent: 280,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Mercury-Milan-Premier.JPG/400px-Mercury-Milan-Premier.JPG",
    title: "Mercury Milan",
    class: "Mid-size",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "25 mpg",
    rent: 260,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Audi_Quattro_vl_black.jpg/400px-Audi_Quattro_vl_black.jpg",
    title: "Audi Quattro",
    start_production: 1980,
    class: "Mid-size car, rally car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 4,
    mileage: "23 mpg",
    rent: 380,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Volvo_V40_2012_ID42221_280212.jpg/400px-Volvo_V40_2012_ID42221_280212.jpg",
    title: "Volvo V40 (P1)",
    start_production: 2012,
    class: "Compact car / Small family car",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "29 mpg",
    rent: 320,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/LincolnAviator.jpg/400px-LincolnAviator.jpg",
    title: "Lincoln Aviator",
    start_production: 2002,
    class: "Mid-size luxury SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 7,
    mileage: "18 mpg",
    rent: 450,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Jeep_Grand_Cherokee_SRT_-_20091127.jpg/400px-Jeep_Grand_Cherokee_SRT_-_20091127.jpg",
    title: "Jeep Grand Cherokee (WK2)",
    start_production: 2010,
    class: "Mid-size SUV",
    fuel: "Gasoline",
    transmission: "Automatic",
    capacity: 5,
    mileage: "21 mpg",
    rent: 350,
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Daewoo_Lanos_1.6_SX_hatch_rear.jpg/400px-Daewoo_Lanos_1.6_SX_hatch_rear.jpg",
    title: "Daewoo Lanos",
    start_production: 1996,
    class: "Subcompact car",
    fuel: "Gasoline",
    transmission: "Manual",
    capacity: 5,
    mileage: "27 mpg",
    rent: 200,
  },
];

export default data;
